package cleaner

import (
	"os"
	"path/filepath"
	"strings"
)

// RiskLevel indicates how safe an item is to delete
type RiskLevel string

const (
	RiskSafe        RiskLevel = "safe"        // Completely safe, automatically regenerated
	RiskRecommended RiskLevel = "recommended" // Very safe, minor rebuild time penalty
	RiskCaution     RiskLevel = "caution"     // May require re-login or full re-download
)

// CleanTarget defines a known cleanable location or rule
type CleanTarget struct {
	ID          string    `json:"id"`
	Category    string    `json:"category"`    // "developer", "system", "app-cache"
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Path        string    `json:"path"`        // Template path with ~
	Risk        RiskLevel `json:"risk"`
	Size        uint64    `json:"size"`
	SizeStr     string    `json:"sizeStr"`
	ItemCount   int64     `json:"itemCount"`
	Exists      bool      `json:"exists"`
	Selected    bool      `json:"selected"`    // Default selected in UI
	Resolved    string    `json:"resolved"`    // Expanded absolute path
	CleanCmd    string    `json:"cleanCmd"`    // Optional command instead of rm
}

// ExpandPath expands ~ to the user's home directory
func ExpandPath(p string) string {
	if strings.HasPrefix(p, "~/") || p == "~" {
		home, err := os.UserHomeDir()
		if err == nil {
			if p == "~" {
				return home
			}
			return filepath.Join(home, p[2:])
		}
	}
	return p
}

// GetPredefinedTargets returns the curated list of macOS & developer clean targets
func GetPredefinedTargets() []CleanTarget {
	return []CleanTarget{
		// Developer: Xcode
		{
			ID:          "xcode-previews",
			Category:    "developer",
			Name:        "Xcode SwiftUI Previews",
			Description: "SwiftUI Canvas önizleme önbellekleri. Xcode bunları gerektiğinde yeniden üretir.",
			Path:        "~/Library/Developer/Xcode/UserData/Previews",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "xcode-deriveddata",
			Category:    "developer",
			Name:        "Xcode DerivedData",
			Description: "Xcode derleme çıktıları ve indeksler. Projelerinizi bir sonraki derlemede yeniden derler.",
			Path:        "~/Library/Developer/Xcode/DerivedData",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "xcode-archives",
			Category:    "developer",
			Name:        "Xcode Archives",
			Description: "Eski derlenmiş ve paketlenmiş uygulama arşivleri.",
			Path:        "~/Library/Developer/Xcode/Archives",
			Risk:        RiskCaution,
			Selected:    false,
		},
		{
			ID:          "xcode-devicesupport",
			Category:    "developer",
			Name:        "iOS Device Support",
			Description: "Eski iOS sürümlerine ait hata ayıklama sembolleri.",
			Path:        "~/Library/Developer/Xcode/iOS DeviceSupport",
			Risk:        RiskRecommended,
			Selected:    true,
		},
		{
			ID:          "xcode-doc-cache",
			Category:    "developer",
			Name:        "Xcode Documentation Cache",
			Description: "İndirilen ve önbelleğe alınan Xcode dokümantasyon verileri.",
			Path:        "~/Library/Developer/Xcode/DocumentationCache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "ios-simulators-cache",
			Category:    "developer",
			Name:        "iOS Simülatör Önbellekleri",
			Description: "Kullanılmayan simülatör geçici dosyaları.",
			Path:        "~/Library/Developer/CoreSimulator/Caches",
			Risk:        RiskSafe,
			Selected:    true,
		},

		// Developer: Package Managers & Languages
		{
			ID:          "gradle-caches",
			Category:    "developer",
			Name:        "Gradle Önbellekleri",
			Description: "İndirilen Gradle bağımlılıkları ve derleme önbellekleri (~/.gradle/caches).",
			Path:        "~/.gradle/caches",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "homebrew-cache",
			Category:    "developer",
			Name:        "Homebrew İndirme Önbelleği",
			Description: "İndirilmiş paket arşivleri ve şişeler (bottles). 'brew cleanup' eşdeğeridir.",
			Path:        "~/Library/Caches/Homebrew",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "go-build-cache",
			Category:    "developer",
			Name:        "Go Derleme Önbelleği (go-build)",
			Description: "Go derleyicisinin derleme önbelleği. 'go clean -cache' eşdeğeridir.",
			Path:        "~/Library/Caches/go-build",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "go-mod-cache",
			Category:    "developer",
			Name:        "Go Modül İndirme Önbelleği",
			Description: "İndirilen Go modüllerinin önbelleği (~/go/pkg/mod/cache).",
			Path:        "~/go/pkg/mod/cache",
			Risk:        RiskRecommended,
			Selected:    false,
		},
		{
			ID:          "npm-cache",
			Category:    "developer",
			Name:        "npm Paket Önbelleği",
			Description: "npm paket indirme önbelleği (~/.npm/_cacache).",
			Path:        "~/.npm/_cacache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "yarn-cache",
			Category:    "developer",
			Name:        "Yarn Paket Önbelleği",
			Description: "Yarn paket indirme önbelleği.",
			Path:        "~/Library/Caches/Yarn",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "pnpm-cache",
			Category:    "developer",
			Name:        "pnpm Önbelleği",
			Description: "pnpm geçici paket önbellekleri.",
			Path:        "~/Library/Caches/pnpm",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "cocoapods-cache",
			Category:    "developer",
			Name:        "CocoaPods Önbelleği",
			Description: "iOS bağımlılıkları indirme önbelleği.",
			Path:        "~/Library/Caches/CocoaPods",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "pip-cache",
			Category:    "developer",
			Name:        "Python Pip Önbelleği",
			Description: "Python pip paket indirme önbelleği.",
			Path:        "~/Library/Caches/pip",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "cargo-cache",
			Category:    "developer",
			Name:        "Rust Cargo Önbelleği",
			Description: "Rust kütüphane indirme önbelleği (~/.cargo/registry/cache).",
			Path:        "~/.cargo/registry/cache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "arduino-staging",
			Category:    "developer",
			Name:        "Arduino Paket İndirme Arşivi (Staging)",
			Description: "İndirilmiş Arduino kart ve çekirdek paketleri. Kurulum sonrasında güvenle temizlenebilir (~2.9 GB).",
			Path:        "~/Library/Arduino15/staging",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "android-system-images",
			Category:    "developer",
			Name:        "Android Emülatör Sistem İmajları",
			Description: "Android Studio sanal cihazları için indirilmiş Google APIs / Play Store imajları (~4.1 GB).",
			Path:        "~/Library/Android/sdk/system-images",
			Risk:        RiskRecommended,
			Selected:    false,
		},
		{
			ID:          "android-avd",
			Category:    "developer",
			Name:        "Android Sanal Cihazları (AVD Kalıpları)",
			Description: "Kullanılmayan Android Studio emülatör sanal diskleri.",
			Path:        "~/.android/avd",
			Risk:        RiskCaution,
			Selected:    false,
		},
		{
			ID:          "vscode-cached-vsix",
			Category:    "developer",
			Name:        "VS Code Eklenti Kurulum Arşivi (VSIX)",
			Description: "VS Code tarafından indirilen eklenti kurulum paketleri (CachedExtensionVSIXs).",
			Path:        "~/Library/Application Support/Code/CachedExtensionVSIXs",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "vscode-app-cache",
			Category:    "developer",
			Name:        "VS Code Uygulama Önbelleği",
			Description: "VS Code webview, GPU ve geçici çalışma önbellekleri.",
			Path:        "~/Library/Application Support/Code/Cache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-screenshots",
			Category:    "developer",
			Name:        "Antigravity Ekran Görüntüleri ve Medya Dosyaları",
			Description: "Ajan oturumlarında ve görsel testlerde üretilen ekran görüntüleri (.tempmediaStorage, *.png, *.webp, *.jpg).",
			Path:        "~/.gemini/antigravity-ide/brain",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-recordings",
			Category:    "developer",
			Name:        "Antigravity Tarayıcı Video & Oturum Kayıtları",
			Description: "Web subagent test ve tarayıcı oturumlarında kaydedilen binlerce ekran karesi ve WebP video oturumları.",
			Path:        "~/.gemini/antigravity-ide/browser_recordings",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-browser-cache",
			Category:    "developer",
			Name:        "Antigravity Ajan Tarayıcı Önbelleği",
			Description: "Headless tarayıcı profilinin biriktirdiği web, stil ve V8 kod önbellekleri (~/.gemini/antigravity-browser-profile).",
			Path:        "~/.gemini/antigravity-browser-profile/Default/Cache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-scratch",
			Category:    "developer",
			Name:        "Antigravity Geçici Çalışma Dosyaları (Scratch)",
			Description: "Ajanların görev sırasında ürettiği geçici test, veri kazıma ve kodlama çalışma dosyaları (~/.gemini/antigravity-ide/scratch).",
			Path:        "~/.gemini/antigravity-ide/scratch",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-ide-cache",
			Category:    "developer",
			Name:        "Antigravity IDE Dahili Çalışma Önbellekleri",
			Description: "IDE dahili webview, GPU ve V8 derleme önbellekleri (~/Library/Caches/com.google.antigravity-ide).",
			Path:        "~/Library/Caches/com.google.antigravity-ide",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-cached-vsix",
			Category:    "developer",
			Name:        "Antigravity Eklenti Kurulum Arşivi (VSIX)",
			Description: "Antigravity IDE tarafından indirilen eklenti paketleri (CachedExtensionVSIXs).",
			Path:        "~/Library/Application Support/Antigravity IDE/CachedExtensionVSIXs",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "puppeteer-cache",
			Category:    "developer",
			Name:        "Puppeteer Otomatik Tarayıcı İndirmeleri",
			Description: "Puppeteer test ve otomasyon motoru tarafından indirilen bağımsız Chromium derlemeleri (~/.cache/puppeteer).",
			Path:        "~/.cache/puppeteer",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "playwright-go-cache",
			Category:    "developer",
			Name:        "Playwright Web Sürücüleri Önbelleği",
			Description: "Playwright otomasyon motoru tarafından indirilen web sürücüleri ve tarayıcı ikilileri (~/Library/Caches/ms-playwright-go).",
			Path:        "~/Library/Caches/ms-playwright-go",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "nuget-cache",
			Category:    "developer",
			Name:        "NuGet Paket ve Derleme Önbelleği",
			Description: ".NET ve C# projelerinin indirdiği yerel bağımlılık ve paket arşivleri (~/.local/share/NuGet).",
			Path:        "~/.local/share/NuGet",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "postman-partitions-cache",
			Category:    "developer",
			Name:        "Postman Webview & Service Worker Önbelleği",
			Description: "Postman masaüstü uygulamasının webview, Service Worker ve GPU çalışma önbellekleri (~/Library/Application Support/Postman/Partitions).",
			Path:        "~/Library/Application Support/Postman/Partitions",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "vscode-crashpad",
			Category:    "developer",
			Name:        "VS Code Crashpad Çökme Raporları",
			Description: "VS Code tarafından kaydedilen minidump ve hata dökümleri (~/Library/Application Support/Code/Crashpad).",
			Path:        "~/Library/Application Support/Code/Crashpad",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "gopls-cache",
			Category:    "developer",
			Name:        "Go Dil Sunucusu Önbelleği (gopls)",
			Description: "Go dili sembol indeksleme, tip analizi ve sözdizimi önbelleği (~/Library/Caches/gopls).",
			Path:        "~/Library/Caches/gopls",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "typescript-cache",
			Category:    "developer",
			Name:        "TypeScript Dil Sunucusu Önbelleği (TSServer)",
			Description: "Kod editörlerinin tuttuğu otomatik tip tanımları ve TypeScript sembol önbellekleri (~/Library/Caches/typescript).",
			Path:        "~/Library/Caches/typescript",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "figma-profile-cache",
			Category:    "developer",
			Name:        "Figma Eski Sürüm Profil Önbellekleri",
			Description: "Figma güncellemeleri sonrası kalan eski sürüm profil ve GPU önbellekleri (~/Library/Application Support/Figma/DesktopProfile).",
			Path:        "~/Library/Application Support/Figma/DesktopProfile",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "vscode-obsolete-extensions",
			Category:    "developer",
			Name:        "VS Code Eski / Yinelenen Eklenti Sürümleri",
			Description: "VS Code güncellemeleri sonrası silinmeyip biriken eski eklenti sürümleri (~/.vscode/extensions).",
			Path:        "~/.vscode/extensions",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "gradle-wrapper-dists",
			Category:    "developer",
			Name:        "Gradle Wrapper İndirme Arşivleri",
			Description: "Gradle wrapper tarafından otomatik indirilen eski Gradle zip dağıtım paketleri (~/.gradle/wrapper/dists).",
			Path:        "~/.gradle/wrapper/dists",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "nuget-user-packages",
			Category:    "developer",
			Name:        "NuGet Kullanıcı Dizin Paketleri",
			Description: "Kullanıcı ana dizininde depolanan .NET/NuGet paket önbelleği (~/.nuget/packages).",
			Path:        "~/.nuget/packages",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "clang-compiler-cache",
			Category:    "developer",
			Name:        "Clang C/C++ Derleyici ve Modül Önbelleği",
			Description: "Kullanıcı geçici dizininde biriken Clang derleyici ve modül önbellekleri (~/.cache/clang).",
			Path:        "~/.cache/clang",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "android-cache",
			Category:    "developer",
			Name:        "Android Studio & SDK Önbelleği",
			Description: "Android Studio derleme ve gradle eklenti önbellekleri (~/.android/cache).",
			Path:        "~/.android/cache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "jetbrains-caches",
			Category:    "developer",
			Name:        "JetBrains IDE Dizin ve Kod İndeksleri",
			Description: "IntelliJ, PyCharm, WebStorm, CLion ve GoLand IDE'lerinin biriktirdiği proje indeksleri ve önbellekler (~/Library/Caches/JetBrains).",
			Path:        "~/Library/Caches/JetBrains",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "sccache-cache",
			Category:    "developer",
			Name:        "Rust / C++ sccache Derleme Önbelleği",
			Description: "Mozilla sccache paylaşımlı derleme önbelleği (~/Library/Caches/Mozilla.sccache).",
			Path:        "~/Library/Caches/Mozilla.sccache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "ccache-cache",
			Category:    "developer",
			Name:        "C/C++ ccache Derleme Önbelleği",
			Description: "C ve C++ projeleri derleme önbelleği (~/.ccache).",
			Path:        "~/.ccache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "docker-desktop-logs",
			Category:    "developer",
			Name:        "Docker Desktop Uygulama Logları & Dökümleri",
			Description: "Docker Desktop macOS servislerinin oluşturduğu geçici hata günlükleri ve log dosyaları.",
			Path:        "~/Library/Containers/com.docker.docker/Data/log",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "chrome-serviceworker-cache",
			Category:    "system",
			Name:        "Google Chrome Service Worker Önbelleği",
			Description: "Web sitelerinin arka planda depoladığı çevrimdışı ve geçici veriler.",
			Path:        "~/Library/Application Support/Google/Chrome/Default/Service Worker/CacheStorage",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "discord-cache",
			Category:    "system",
			Name:        "Discord Medya ve Görsel Önbelleği",
			Description: "Discord kanallarından indirilen profil resimleri, gifler ve medya önbellekleri.",
			Path:        "~/Library/Application Support/discord/Cache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "steam-appcache",
			Category:    "system",
			Name:        "Steam İstemci & İndirme Önbelleği",
			Description: "Steam geçici indirme ve web arayüzü önbellekleri.",
			Path:        "~/Library/Application Support/Steam/appcache",
			Risk:        RiskSafe,
			Selected:    true,
		},

		// System Junk & App Updates
		{
			ID:          "vscode-shipit",
			Category:    "system",
			Name:        "VS Code Güncelleme Artıkları (ShipIt)",
			Description: "VS Code otomatik güncelleme indiricisine ait eski kurulum paketleri.",
			Path:        "~/Library/Caches/com.microsoft.VSCode.ShipIt",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "google-cache",
			Category:    "system",
			Name:        "Google / Chrome Önbellek Artıkları",
			Description: "Chrome ve Google servislerine ait geçici indirme ve önbellek dosyaları.",
			Path:        "~/Library/Caches/Google",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "adobe-cache",
			Category:    "system",
			Name:        "Adobe Geçici Önbellekleri",
			Description: "Adobe Creative Cloud ve uygulamalarına ait geçici dosyalar.",
			Path:        "~/Library/Caches/Adobe",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-shipit",
			Category:    "system",
			Name:        "Antigravity / IDE Güncelleme Artıkları",
			Description: "Eski IDE güncelleme indiricisi paketleri ve geçici dosyalar.",
			Path:        "~/Library/Caches/com.google.antigravity.ShipIt",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "antigravity-updater",
			Category:    "system",
			Name:        "Antigravity Güncelleyici Önbelleği",
			Description: "Arka plan güncelleme önbelleği.",
			Path:        "~/Library/Caches/antigravity-updater",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "crossover-cache",
			Category:    "system",
			Name:        "CrossOver Geçici Dosyaları",
			Description: "CrossOver şişeleme ve indirme önbelleği.",
			Path:        "~/Library/Caches/com.codeweavers.CrossOver",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "phpwebstudy-updater",
			Category:    "system",
			Name:        "PhpWebStudy Güncelleyici Önbelleği",
			Description: "Eski güncelleme indiricisi dosyaları.",
			Path:        "~/Library/Caches/phpwebstudy-updater",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "freecad-cache",
			Category:    "system",
			Name:        "FreeCAD Önbelleği",
			Description: "FreeCAD geçici hesaplama ve render önbelleği.",
			Path:        "~/Library/Caches/FreeCAD",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "epicgames-cache",
			Category:    "system",
			Name:        "Epic Games Launcher Önbelleği",
			Description: "Epic Games Launcher web görünümü ve geçici indirme önbelleği.",
			Path:        "~/Library/Caches/com.epicgames.EpicGamesLauncher",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "steam-cache",
			Category:    "system",
			Name:        "Steam İstemci Önbelleği",
			Description: "Steam web tarayıcısı ve önbellek dosyaları.",
			Path:        "~/Library/Caches/Steam",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "system-logs",
			Category:    "system",
			Name:        "Kullanıcı ve Uygulama Günlükleri (Logs)",
			Description: "Zamanla biriken hata, çökme raporları ve teşhis logları.",
			Path:        "~/Library/Logs",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "trash-bin",
			Category:    "system",
			Name:        "macOS Çöp Kutusu",
			Description: "Çöp kutusunda bekleyen ve diskte yer kaplayan dosyalar.",
			Path:        "~/.Trash",
			Risk:        RiskRecommended,
			Selected:    true,
		},
		{
			ID:          "quicklook-cache",
			Category:    "system",
			Name:        "QuickLook Küçük Resim Önbelleği",
			Description: "macOS Finder önizleme ve küçük resim önbelleği.",
			Path:        "~/Library/Caches/com.apple.QuickLook.thumbnailcache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "macos-aerials-wallpaper",
			Category:    "system",
			Name:        "macOS 4K Aerials Ekran Koruyucuları",
			Description: "macOS Sonoma ve Sequoia'nın indirdiği yüksek çözünürlüklü ekran koruyucu ve duvar kağıdı video arşivi.",
			Path:        "~/Library/Application Support/com.apple.wallpaper/aerials",
			Risk:        RiskRecommended,
			Selected:    true,
		},
		{
			ID:          "macos-geoservices-cache",
			Category:    "system",
			Name:        "Apple Harita ve Konum Önbelleği (GeoServices)",
			Description: "Apple Haritalar çevrimdışı harita karoları, rota ve yer verisi önbellekleri (~/Library/Caches/GeoServices).",
			Path:        "~/Library/Caches/GeoServices",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "macos-mediaanalysis-cache",
			Category:    "system",
			Name:        "Apple Fotoğraflar Medya Analiz Önbelleği",
			Description: "Fotoğraflar uygulamasının yüz, sahne ve coğrafi konum analizi geçici indeksleri.",
			Path:        "~/Library/Containers/com.apple.mediaanalysisd/Data/Library/Caches",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "macos-helpd-cache",
			Category:    "system",
			Name:        "macOS Yardım Kılavuzları Önbelleği (helpd)",
			Description: "macOS Yardım belgelerinin indirilmiş HTML ve görsel içerik önbellekleri (~/Library/Caches/com.apple.helpd).",
			Path:        "~/Library/Caches/com.apple.helpd",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "macos-parsecd-cache",
			Category:    "system",
			Name:        "Siri & Spotlight Arama Önbelleği (parsecd)",
			Description: "Spotlight ve Siri önerileri ile web arama sorguları önbelleği (~/Library/Caches/com.apple.parsecd).",
			Path:        "~/Library/Caches/com.apple.parsecd",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "macos-diagnostic-reports",
			Category:    "system",
			Name:        "Kullanıcı Teşhis ve Çökme Raporları",
			Description: "Çöken veya yanıt vermeyen uygulamalara ait hata dökümleri ve raporlar (~/Library/Logs/DiagnosticReports).",
			Path:        "~/Library/Logs/DiagnosticReports",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "macos-saved-application-state",
			Category:    "system",
			Name:        "Kayıtlı Uygulama Pencere Durumları",
			Description: "Kapanan uygulamaların pencere konumları ve oturum kalıntıları (~/Library/Saved Application State).",
			Path:        "~/Library/Saved Application State",
			Risk:        RiskRecommended,
			Selected:    false,
		},
		{
			ID:          "adobe-media-cache",
			Category:    "system",
			Name:        "Adobe Ortak Medya Önbelleği (Media Cache)",
			Description: "Photoshop, Premiere ve After Effects tarafından oluşturulan piksel ve ses önbellekleri (~/Library/Application Support/Adobe/Common).",
			Path:        "~/Library/Application Support/Adobe/Common",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "adobe-uxp-cache",
			Category:    "system",
			Name:        "Adobe UXP Eklenti ve Çalışma Önbelleği",
			Description: "Adobe Creative Cloud UXP eklenti motoru geçici çalışma dosyaları (~/Library/Application Support/Adobe/UXP).",
			Path:        "~/Library/Application Support/Adobe/UXP",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "epicgames-launcher-data",
			Category:    "system",
			Name:        "Epic Games Launcher İndirme ve Veri Önbelleği",
			Description: "Epic Games Launcher'ın web görünümü, EMS indirme parçaları ve geçici verileri (~/Library/Application Support/Epic/EpicGamesLauncher/Data).",
			Path:        "~/Library/Application Support/Epic/EpicGamesLauncher/Data",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "battlenet-cache",
			Category:    "system",
			Name:        "Blizzard Battle.net Başlatıcı Önbellekleri",
			Description: "Battle.net istemcisinin web tarayıcısı ve güncelleme önbellekleri (~/Library/Application Support/Battle.net/Cache).",
			Path:        "~/Library/Application Support/Battle.net/Cache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "discord-logs-cache",
			Category:    "system",
			Name:        "Discord Günlükleri ve Eklenti Önbelleği",
			Description: "Discord masaüstü uygulamasının biriktirdiği hata/teşhis logları (~/Library/Application Support/discord/logs).",
			Path:        "~/Library/Application Support/discord/logs",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "msoffice-font-cache",
			Category:    "system",
			Name:        "Microsoft Office Yazı Tipi Önbelleği",
			Description: "Word, Excel ve PowerPoint yazı tipi ve eklenti paketleri önbelleği (~/Library/Group Containers/UBF8T346G9.Office/FontCache).",
			Path:        "~/Library/Group Containers/UBF8T346G9.Office/FontCache",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "macos-cores-dump",
			Category:    "system",
			Name:        "Sistem Çekirdek Çökme Dökümleri (/cores)",
			Description: "macOS veya uygulamalar çöktüğünde /cores dizinine yazılan devasa bellek dökümleri (core dump).",
			Path:        "/cores",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "anydesk-incoming",
			Category:    "system",
			Name:        "AnyDesk Gelen Dosyalar ve Oturum Artıkları",
			Description: "AnyDesk uzak masaüstü oturumları üzerinden aktarılmış eski dosyalar (~/.anydesk/incoming).",
			Path:        "~/.anydesk/incoming",
			Risk:        RiskRecommended,
			Selected:    false,
		},
		{
			ID:          "anydesk-thumbnails",
			Category:    "system",
			Name:        "AnyDesk Oturum Önizleme Resimleri",
			Description: "AnyDesk uzak oturum bağlantılarına ait küçük resim önbellekleri (~/.anydesk/thumbnails).",
			Path:        "~/.anydesk/thumbnails",
			Risk:        RiskSafe,
			Selected:    true,
		},
		{
			ID:          "zsh-sessions-history",
			Category:    "system",
			Name:        "Terminal Oturum Geçmişi Kopyaları (zsh_sessions)",
			Description: "Her terminal sekmesi kapandığında kaydedilen yinelenen komut geçmişi kopyaları (~/.zsh_sessions).",
			Path:        "~/.zsh_sessions",
			Risk:        RiskSafe,
			Selected:    true,
		},
	}
}
